' 2.15.1 Business Usecase
@startuml
	(First usecase)/
	(Another usecase)/ as (UC2)
	usecase/ UC3
	usecase/ (Last\nusecase) as UC4
@enduml

' 2.15.2 Business Actor
@startuml
	:First Actor:/
	:Another\nactor:/ as Man2
	actor/ Woman3
	actor/ :Last actor: as Person1
@enduml
