@startuml
	class Dummy1 {
		+myMethods()
	}
	class Dummy2 {
		+hiddenMethod()
	}
	class Dummy3 <<Serializable>> {
		String name
	}
	hide members
	hide <<Serializable>> circle
	show Dummy1 methods
	show <<Serializable>> fields
@enduml

@startuml
	hide private members
	hide protected members
	hide package members
	class Foo {
		- private
		# protected
		~ package
	}
@enduml